#!/bin/bash

set -e

setup_git_credentials_for_container() {
  if ! [[ -z "$GIT_KEY" ]]; then
    eval "$(ssh-agent -s)"
    echo "$GIT_KEY" > ./git-key.pem 
    chmod 600 ./git-key.pem
    ssh-add ./git-key.pem
    mkdir -p ~/.ssh
    ssh-keyscan github.com >> ~/.ssh/known_hosts

    git config --global user.name pcf-toronto-ci-bot
    git config --global user.email tpt-team+cibot@pivotal.io
  fi
}
